### ISSUE TITLE
无限循环的问题

### ISSUE THREAD

**Issue by ghost** [moonshine57/Moments_wordCloud#1]
![image](https://user-images.githubusercontent.com/23503313/67509379-6e3d1d80-f6c5-11e9-8a9b-7f051475e303.png)

**Comment by moonshine57** [comment]
你的f1v标签代表的是界面的什么组件呢，如果再下拉的过程中一直捕获这个组件，就会无限循环。我代码中的该组件是指年份文本，比如我想获取2019年一整年的朋友圈信息，那我代码中的ekg是指“2018年”这个文本，当捕获到“2018年”的时候，上拉速度变慢；当“2018年”消失在界面中时，跳出循环。
![4a7428026acc527b09f975488fd5fdb](https://user-images.githubusercontent.com/49117938/70489901-ebb6d300-1b37-11ea-8cb8-9793a4aa2775.jpg)

**Comment by moonshine57** [comment]
你的f1v标签指的是界面的什么组件呢，在我的代码中，该组件是年份文本。比如我想获取2019年一整年的朋友圈，当我获取到“2018年”这个文本时，上拉速度变慢；当“2018年”这个文本消失在界面后，跳出循环。
![48827640b3fd39cb7006b23cca9173d](https://user-images.githubusercontent.com/49117938/70490247-dee6af00-1b38-11ea-8c2e-328ed5b6828c.png)

**Comment by roothch** [comment]
你的f1v标签指的是界面的什么组件呢，在我的代码中，该组件是年份文本。比如我想获取2019年一整年的朋友圈，当我获取到“2018年”这个文本时，上拉速度变慢；当“2018年”这个文本消失在界面后，跳出循环。
![image](https://user-images.githubusercontent.com/49117938/70490443-50bef880-1b39-11ea-8408-46ca18463cbc.png)
